  [[main]]
  name = "Home"
  identifier = "home"
  weight = 100
  url = "/"

  [[main]]
  name = "Posts"
  weight = 200
  identifier = "posts"
  url = "/post/"

  [[main]]
  name = "About"
  weight = 300
  identifier = "about"
  url = "/about/"

  [[main]]
  name = "Certifications"
  weight = 400
  identifier = "certifications"
  url = "/certifications/"
  
  [[main]]
  name = "Links"
  weight = 500
  identifier = "links"
  url = "/links"

  [[main]]
  name = "Tech Podcasts"
  weight = 510
  identifier = "tech podcasts"
  url = "/tech_podcasts"
  parent = "links"

  [[main]]
  name = "Veteran Resources"
  weight = 520
  identifier = "veteran resources"
  url = "/veteran_resources"
  parent = "links"

  [[main]]
  name = "Portfolio"
  weight = 210
  identifier = "portfolio"
  url = "/portfolio"

  [[main]]
  name = "Home Lab Network Project - Version 1"
  weight = 220
  identifier = "home lab network project - version 1"
  url = "/portfolio/home_lab_network_project/v1"
  parent = "portfolio"

  #[[main]]
  #name = "Accomplishments"
  #weight = 500
  #identifier = "accomplishments"

  #[[main]]
  #name = "Awards"
  #weight = 510
  #identifier = "awards"
  #url = "/awards/"
  #parent = "accomplishments"  

  #[[main]]
  #name = "Contact"
  #weight = 600
  #identifier = "contact"
  #url = "/contact/"

  #[[footer]]
  #name = "imprint"
  #weight = 1
  #identifier = "imprint"
  #url = "/imprint/"
